spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 5
  data:
    mongodb:
      uri: mongodb://user:pass@localhost:27017/hediapps
eureka:
  client:
    enabled: false
